Repository stolostron/search-chart, pull requests merged in 2021-06, with the labels that each got.

#108 Update aggregator permissions for klusterletaddonconfigs
  stable/search-prod/templates/aggregator-role.yaml
Labels: approved, lgtm

#111 Add RELEASE_NAME to operator
  stable/search-prod/templates/operator-deployment.yaml
Labels: approved, lgtm

#112 [2.2] add Release_Name env to operator deployment
  stable/search-prod/templates/operator-deployment.yaml
Labels: do-not-merge/hold, lgtm

#113 cd into new repo name
  .travis.yml
Labels: lgtm

#114 [release-2.2] Point to multiclusterhub-repo release-2.2 branch
  .travis.yml
Labels: lgtm
